openapi: "3.0.1"
info:
  title: "AWS-SQS-Jobs"
  version: "2020-08-20T12:57:36Z"
paths:
  /jobs/{jobId}:
    get:
      parameters:
        - name: "jobId"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      x-amazon-apigateway-integration:
        type: "aws"
        credentials: "${apig_role}"
        uri: "arn:aws:apigateway:us-east-1:dynamodb:action/GetItem"
        httpMethod: "POST"
        responses:
          default:
            statusCode: "200"
            responseTemplates:
              application/json: ${get_job_by_id_response_mapping_template}
        requestTemplates:
          application/json: ${get_job_by_id_request_mapping_template}
        passthroughBehavior: "when_no_templates"
  /jobs:
    get:
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      x-amazon-apigateway-integration:
        type: "aws"
        credentials: "${apig_role}"
        uri: "arn:aws:apigateway:us-east-1:dynamodb:action/Scan"
        httpMethod: "POST"
        responses:
          default:
            statusCode: "200"
            responseTemplates:
              application/json: ${get_jobs_response_mapping_template}
        requestTemplates:
          application/json: ${get_jobs_request_mapping_template}
        passthroughBehavior: "when_no_templates"
    post:
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      x-amazon-apigateway-integration:
        credentials: "${apig_role}"
        uri: "${apig_invocation_uri}"
        httpMethod: "POST"
        responses:
          default:
            statusCode: "200"
            responseTemplates:
              application/json: ${post_jobs_response_mapping_template}
        requestParameters:
          integration.request.header.Content-Type: "'application/x-www-form-urlencoded'"
        requestTemplates:
          application/json: "Action=SendMessage&MessageBody=$input.body&MessageAttribute.1.Name=foo&MessageAttribute.1.Value.DataType=String&MessageAttribute.1.Value.StringValue=bar"
        passthroughBehavior: "never"
        type: "aws"
components:
  schemas:
    Empty:
      title: "Empty Schema"
      type: "object"
  securitySchemes:
    sigv4:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "awsSigv4"
